### ISSUE TITLE
task4 问题

### ISSUE THREAD

**Issue by wagnlinzh** [FED-Div/task4#1]
我弄了两个版本的,task4.html是主要用了flex,task4_2.html中用的是absolute定位

使用flex的时候遇到了一个问题,设置了水平居中,但是不能设置垂直居中,怎么搞?

``` css
.flexcontent{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
```

地址:
task4.html: http://fed-div.github.io/task4/task4.html

task4_2.html: http://fed-div.github.io/task4/task4_2.html
